### ISSUE TITLE
Support for launching specified editor in the process ?

### ISSUE THREAD

**Issue by Orange-C** [yyx990803/launch-editor#15]
For some people who don't use command line tools for editor.

I already created [launch-code-editor](https://github.com/Orange-C/launch-code-editor) to temporarily solve my [case](https://github.com/alibaba/ice/pull/2360)

I'll be appreciated if `launch-editor` is interested in supporting this feature. I'll create a PR when needed.

**Comment by chrisfromredfin** [comment]
+1 on this. I would like either (a) to be able to specify the preference / order to try the applications in, or (b) be able to have it respect EDITOR if set FIRST, and THEN fall back to guessing from running apps.

My particular case is that I often run Sublime Text and VS Code for two different reasons (and prefer VS Code as the code editor), but since VS Code appears later in the osx.js it opens in Sublime instead of VS Code as that's the first one it finds. 

I wonder if in the package.json I could specify the order as it was specified in, say, osx.js and it would read that and then fall back to the default file if not found?

I also see that you're fundamentally doing the same by checking process.versions.webcontainer, and I wonder if I could somehow specify process.versions.webcontainer TRUE somewhere on my own, but I can't find anything about how to SET process.versions, only how to read it.

**Comment by chrisfromredfin** [comment]
Alternatively, something like being able to specify `"forceEditor": TRUE` and then the line becomes:

```javascript
if (process.versions.webcontainer || forceEditor) {...}
```

**Comment by dominikg** [comment]
maybe fixed by https://github.com/yyx990803/launch-editor/pull/39

**Comment by sodatea** [comment]
Released as 2.6.0
