### ISSUE TITLE
feat: add filename validation for windows

### ISSUE THREAD

**Issue by dominikg** [yyx990803/launch-editor#50]
The vue-inspector by @webfansplz contains code that prevents some filenames from being opened with a shell command

https://github.com/webfansplz/vite-plugin-vue-inspector/blob/main/src/launch-editor.ts#L336-L357

This is to prevent possible attacks where a crafted filename could be used to execute malicious commands.

Currently launch-editor does not have a check like this. It's hard to exploit because there is an `fs.existsSync` check but for defense in depth it would be better to not let these kinds of filenames through

The regex here https://github.com/webfansplz/vite-plugin-vue-inspector/blob/main/src/launch-editor.ts#L108-L112  looks longish, maybe a smaller list of forbidden chars does the trick too

**Comment by sodatea** [comment]
These are basically backports of https://github.com/facebook/create-react-app/pull/4866 and https://github.com/facebook/create-react-app/pull/5431
As Unicode character class escape has been supported since Node.js 10[^1], I think we can use the uncompiled version here.

The only remaining problem is that this RegExp can't be parsed with our current ESLint setup.
I'll try to fix this issue when I have the time to move away from `eslint-plugin-vue-libs` and bump the ESLint major version in this repository.

[^1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape

**Comment by dominikg** [comment]
@sodatea your fix for this broke svelte-inspector for sveltekit +page files: https://github.com/sveltejs/vite-plugin-svelte/issues/943#issuecomment-2227519952

is + an exploitable char in windows filenames?

**Comment by sodatea** [comment]
After reading https://stackoverflow.com/q/4094699/2302258, I believe it's not exploitable.
Let me think this validation logic over. It might be better to escape than validate.

**Comment by dominikg** [comment]
expanding the safe chars list or switching to only blocking bad chars both seem fine to me too, but if there is a way to properly escape the path before sending it to cmd thats even better

**Comment by oneezy** [comment]
this should be re-opened. we're still getting issues on Win11

### Reference
**issue**: https://github.com/sveltejs/vite-plugin-svelte/issues/943#issuecomment-2308578599

**Comment by Loizzus** [comment]
Can confirm, issue has not been fixed at all for Svelte 4. 
![image](https://github.com/user-attachments/assets/acaeb592-52c5-4cc5-bee6-5a72534cf58d)

Also does not work at all in Svelte 5.
